apiVersion: v1
kind: Service
metadata:
  name: minho-blog
  namespace: minho
  labels:
    app: minho-blog
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: minho-blog
